<script setup lang="ts">
import { reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ArrowRight, Building2 } from '@lucide/vue'
import { useAuthStore } from '../stores/auth'
const auth=useAuthStore(); const router=useRouter(); const loading=ref(false); const error=ref(''); const form=reactive({name:'',email:'',company_name:'',password:'',password_confirmation:''})
async function submit(){loading.value=true;error.value='';try{const {data}=await auth.register(form);router.replace({path:'/verify-email',query:{sent:'1',email:data.email}})}catch(e:any){const errors=e.response?.data?.errors;error.value=errors?Object.values(errors).flat().join(' '):(e.response?.data?.message||'Unable to create workspace.')}finally{loading.value=false}}
</script>
<template><main class="register-page"><div class="register-brand"><div class="brand-mark">E</div><strong>EXOUSIA <span>REALTY</span></strong></div><section class="register-card"><div class="register-icon"><Building2/></div><span class="eyebrow">START YOUR WORKSPACE</span><h1>Build a calmer brokerage.</h1><p>Set up your secure company workspace in under two minutes.</p><form class="form-grid" @submit.prevent="submit"><label>Your name<input v-model="form.name" required placeholder="Beshoy Adel"></label><label>Work email<input v-model="form.email" type="email" required placeholder="you@company.com"></label><label class="full">Brokerage name<input v-model="form.company_name" required placeholder="Your brokerage"></label><label>Password<input v-model="form.password" type="password" required minlength="8"></label><label>Confirm password<input v-model="form.password_confirmation" type="password" required></label><div v-if="error" class="form-error full">{{ error }}</div><button class="button primary wide full" :disabled="loading">{{loading?'Creating workspace…':'Create workspace'}}<ArrowRight :size="18"/></button></form><p class="auth-alt">Already have an account? <RouterLink to="/login">Sign in</RouterLink></p></section></main></template>
