<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { CalendarCheck, Check, Clock3, Plus } from '@lucide/vue'
import { api } from '../api'
import { useAuthStore } from '../stores/auth'; import Modal from '../components/Modal.vue'
import { useTasksStore } from '../stores/tasks'
const auth=useAuthStore();const taskStore=useTasksStore();const tasks=ref<any[]>([]);const loading=ref(true);const showCreate=ref(false);const saving=ref(false);const error=ref('');const form=reactive({title:'',description:'',assigned_to:auth.bootstrap?.user.id||0,priority:'normal',due_at:''})
async function load(){loading.value=true;try{const {data}=await api.get('/tasks');tasks.value=data.data;taskStore.setOpenCount(Number(data.total)||0)}finally{loading.value=false}}
async function toggle(id:number){await api.patch(`/tasks/${id}/complete`);await load()} onMounted(load)
async function create(){saving.value=true;error.value='';try{await api.post('/tasks',form);showCreate.value=false;form.title='';form.description='';form.due_at='';await load()}catch(e:any){error.value=Object.values(e.response?.data?.errors||{error:[e.response?.data?.message||'Unable to create task.']}).flat().join(' ')}finally{saving.value=false}}
const relative=(date:string)=>{const d=new Date(date);const today=new Date();const diff=Math.ceil((d.getTime()-today.getTime())/86400000);return diff<0?`${Math.abs(diff)}d overdue`:diff===0?'Due today':diff===1?'Tomorrow':`In ${diff} days`}
</script>
<template><div><header class="page-heading"><div><span class="eyebrow">FOLLOW-THROUGH</span><h1>Tasks</h1><p>Your focused list of calls, meetings, and follow-ups.</p></div><button class="button primary" @click="showCreate=true"><Plus/>New task</button></header><section class="panel task-page-panel"><div class="task-tabs"><button class="active">Open tasks <span>{{tasks.length}}</span></button></div><div v-if="loading" class="task-loading"><i v-for="n in 4"/></div><div v-else-if="!tasks.length" class="large-empty"><div><CalendarCheck/></div><h2>Your day is clear.</h2><p>There are no outstanding follow-ups for this workspace.</p></div><div v-else class="full-task-list"><article v-for="task in tasks" :key="task.id"><button class="complete-button" @click="toggle(task.id)"><Check/></button><div class="task-body"><strong>{{task.title}}</strong><p v-if="task.description">{{task.description}}</p><div><span v-if="task.lead">{{task.lead.name}}</span><span>{{task.assignee.name}}</span></div></div><time :class="{overdue:new Date(task.due_at)<new Date()}"><Clock3/>{{relative(task.due_at)}}<small>{{new Intl.DateTimeFormat('en-EG',{day:'numeric',month:'short',hour:'numeric',minute:'2-digit'}).format(new Date(task.due_at))}}</small></time></article></div></section><Modal v-if="showCreate" title="Create a follow-up" description="Assign a clear next action and due time." @close="showCreate=false"><form class="form-grid" @submit.prevent="create"><label class="full">Task title<input v-model="form.title" required placeholder="Call client with availability update"></label><label>Assigned to<select v-model="form.assigned_to" required><option v-for="member in auth.bootstrap?.members" :value="member.id">{{member.name}}</option></select></label><label>Priority<select v-model="form.priority"><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option></select></label><label class="full">Due at<input v-model="form.due_at" type="datetime-local" required></label><label class="full">Notes<input v-model="form.description" placeholder="Optional context"></label><div v-if="error" class="form-error full">{{error}}</div><div class="form-actions full"><button type="button" class="button secondary" @click="showCreate=false">Cancel</button><button class="button primary" :disabled="saving">{{saving?'Saving…':'Create task'}}</button></div></form></Modal></div></template>
